import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

function toPosix(p) {
  return p.replaceAll("\\", "/");
}

function normalizePathMode(raw) {
  if (!raw) return "absolute";
  const mode = String(raw).trim().toLowerCase();
  if (mode === "absolute" || mode === "abs") return "absolute";
  if (mode === "relative" || mode === "rel") return "relative";
  return "absolute";
}

function parsePathModeArg(argv) {
  const direct = argv.find((a) => a === "--absolute" || a === "--relative");
  if (direct === "--absolute") return "absolute";
  if (direct === "--relative") return "relative";

  const keyValue = argv.find((a) => a.startsWith("--path-mode="));
  if (keyValue) {
    return normalizePathMode(keyValue.slice("--path-mode=".length));
  }

  return null;
}

function toClangdIncludePath(baseDir, targetPath, pathMode) {
  const absPosix = toPosix(path.resolve(targetPath));
  if (pathMode === "absolute") return absPosix;

  let rel = path.relative(baseDir, targetPath);
  if (!rel || rel.length === 0) rel = ".";
  rel = toPosix(rel);
  if (rel === ".") return ".";
  if (!rel.startsWith(".") && !rel.startsWith("/")) rel = `./${rel}`;
  return rel;
}

function tryGetLocalAppData() {
  if (process.env.LOCALAPPDATA) return process.env.LOCALAPPDATA;
  if (process.env.USERPROFILE) return path.join(process.env.USERPROFILE, "AppData", "Local");
  return null;
}

function parseSemver(v) {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(v);
  if (!m) return null;
  return { major: Number(m[1]), minor: Number(m[2]), patch: Number(m[3]) };
}

function compareSemver(a, b) {
  if (a.major !== b.major) return a.major - b.major;
  if (a.minor !== b.minor) return a.minor - b.minor;
  return a.patch - b.patch;
}

function listNodeCacheIncludeDirs(cacheRoot) {
  const dirs = fs
    .readdirSync(cacheRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .map((name) => ({ name, ver: parseSemver(name) }))
    .filter((x) => x.ver !== null)
    .sort((x, y) => compareSemver(x.ver, y.ver));

  // Prefer the current runtime Node version, then include all other cached versions (newest first).
  const preferred = process.versions.node; // e.g. "24.6.0"
  const orderedVersions = [];
  if (preferred) orderedVersions.push(preferred);

  for (let i = dirs.length - 1; i >= 0; i--) {
    const v = dirs[i].name;
    if (v !== preferred) orderedVersions.push(v);
  }

  const includeDirs = [];
  for (const v of orderedVersions) {
    const inc = path.join(cacheRoot, v, "include", "node");
    if (fs.existsSync(inc)) {
      includeDirs.push(inc);
    }
  }

  // De-dupe while preserving order.
  return [...new Set(includeDirs)];
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const napiPluginDir = path.resolve(__dirname, "..");
const clangdPath = path.join(napiPluginDir, ".clangd");
const require = createRequire(import.meta.url);

const cliPathMode = parsePathModeArg(process.argv.slice(2));
const envPathMode = normalizePathMode(process.env.CLANGD_INCLUDE_PATH_MODE);
const pathMode = cliPathMode ?? envPathMode;

const localAppData = tryGetLocalAppData();
if (!localAppData) process.exit(0);

const cacheRoot = path.join(localAppData, "node-gyp", "Cache");
if (!fs.existsSync(cacheRoot)) process.exit(0);

const nodeIncludeDirs = listNodeCacheIncludeDirs(cacheRoot);
if (nodeIncludeDirs.length === 0) process.exit(0);

const nodeIncludeDirsPosix = nodeIncludeDirs.map((p) => toPosix(p));
const nodeAddonApiPackageJsonPath = require.resolve("node-addon-api/package.json", { paths: [napiPluginDir] });
const nodeAddonApiDir = path.dirname(nodeAddonApiPackageJsonPath);
const nativeSrcDir = path.resolve(napiPluginDir, "../native/src");

const includePaths = [
  toClangdIncludePath(napiPluginDir, nodeAddonApiDir, pathMode),
  toClangdIncludePath(napiPluginDir, nativeSrcDir, pathMode),
  ...nodeIncludeDirsPosix
];

const includeLines = includePaths.map((p) => `    - "-I${p}"`).join("\n");

const content = `CompileFlags:
  Add:
    # Used by clangd only (editor IntelliSense), not by node-gyp builds.
    # Auto-generated by \`napi-plugin/scripts/update-clangd.mjs\`.
    # Path mode: ${pathMode}
    - "-std=c++17"
${includeLines}
    - "-DNAPI_DISABLE_CPP_EXCEPTIONS"
`;

fs.writeFileSync(clangdPath, content, "utf8");
