import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

function toPosix(p) {
  return p.replaceAll("\\", "/");
}

function tryGetLocalAppData() {
  if (process.env.LOCALAPPDATA) return process.env.LOCALAPPDATA;
  if (process.env.USERPROFILE) return path.join(process.env.USERPROFILE, "AppData", "Local");
  return null;
}

function parseSemver(v) {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(v);
  if (!m) return null;
  return { major: Number(m[1]), minor: Number(m[2]), patch: Number(m[3]) };
}

function compareSemver(a, b) {
  if (a.major !== b.major) return a.major - b.major;
  if (a.minor !== b.minor) return a.minor - b.minor;
  return a.patch - b.patch;
}

function listNodeCacheIncludeDirs(cacheRoot) {
  const dirs = fs
    .readdirSync(cacheRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .map((name) => ({ name, ver: parseSemver(name) }))
    .filter((x) => x.ver !== null)
    .sort((x, y) => compareSemver(x.ver, y.ver));

  // Prefer the current runtime Node version, then include all other cached versions (newest first).
  const preferred = process.versions.node; // e.g. "24.6.0"
  const orderedVersions = [];
  if (preferred) orderedVersions.push(preferred);

  for (let i = dirs.length - 1; i >= 0; i--) {
    const v = dirs[i].name;
    if (v !== preferred) orderedVersions.push(v);
  }

  const includeDirs = [];
  for (const v of orderedVersions) {
    const inc = path.join(cacheRoot, v, "include", "node");
    if (fs.existsSync(inc)) {
      includeDirs.push(inc);
    }
  }

  // De-dupe while preserving order.
  return [...new Set(includeDirs)];
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const napiPluginDir = path.resolve(__dirname, "..");
const clangdPath = path.join(napiPluginDir, ".clangd");

const localAppData = tryGetLocalAppData();
if (!localAppData) process.exit(0);

const cacheRoot = path.join(localAppData, "node-gyp", "Cache");
if (!fs.existsSync(cacheRoot)) process.exit(0);

const nodeIncludeDirs = listNodeCacheIncludeDirs(cacheRoot);
if (nodeIncludeDirs.length === 0) process.exit(0);

const nodeIncludeDirsPosix = nodeIncludeDirs.map((p) => toPosix(p));

const nodeIncludeLines = nodeIncludeDirsPosix.map((p) => `    - "-I${p}"`).join("\n");

const content = `CompileFlags:
  Add:
    # Used by clangd only (editor IntelliSense), not by node-gyp builds.
    # Auto-generated by \`napi-plugin/scripts/update-clangd.mjs\`.
    - "-std=c++17"
    - "-I./node_modules/node-addon-api"
    - "-I../native/src"
${nodeIncludeLines}
    - "-DNAPI_DISABLE_CPP_EXCEPTIONS"
`;

fs.writeFileSync(clangdPath, content, "utf8");
