import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

function toPosix(p) {
  return p.replaceAll("\\", "/");
}

function tryGetLocalAppData() {
  if (process.env.LOCALAPPDATA) return process.env.LOCALAPPDATA;
  if (process.env.USERPROFILE) return path.join(process.env.USERPROFILE, "AppData", "Local");
  return null;
}

function parseSemver(v) {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(v);
  if (!m) return null;
  return { major: Number(m[1]), minor: Number(m[2]), patch: Number(m[3]) };
}

function compareSemver(a, b) {
  if (a.major !== b.major) return a.major - b.major;
  if (a.minor !== b.minor) return a.minor - b.minor;
  return a.patch - b.patch;
}

function pickBestNodeCacheVersion(cacheRoot) {
  const preferred = process.versions.node; // e.g. "24.6.0"
  const preferredPath = path.join(cacheRoot, preferred, "include", "node");
  if (fs.existsSync(preferredPath)) return preferred;

  // Fallback: pick highest semver present.
  const dirs = fs
    .readdirSync(cacheRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .map((name) => ({ name, ver: parseSemver(name) }))
    .filter((x) => x.ver !== null)
    .sort((x, y) => compareSemver(x.ver, y.ver));

  for (let i = dirs.length - 1; i >= 0; i--) {
    const candidate = dirs[i].name;
    const inc = path.join(cacheRoot, candidate, "include", "node");
    if (fs.existsSync(inc)) return candidate;
  }

  return null;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const napiPluginDir = path.resolve(__dirname, "..");
const clangdPath = path.join(napiPluginDir, ".clangd");

const localAppData = tryGetLocalAppData();
if (!localAppData) process.exit(0);

const cacheRoot = path.join(localAppData, "node-gyp", "Cache");
if (!fs.existsSync(cacheRoot)) process.exit(0);

const version = pickBestNodeCacheVersion(cacheRoot);
if (!version) process.exit(0);

const nodeInclude = path.join(cacheRoot, version, "include", "node");
const nodeIncludePosix = toPosix(nodeInclude);

const content = `CompileFlags:
  Add:
    # Used by clangd only (editor IntelliSense), not by node-gyp builds.
    # Auto-generated by \`napi-plugin/scripts/update-clangd.mjs\`.
    - "-std=c++17"
    - "-I./node_modules/node-addon-api"
    - "-I../native/src"
    - "-I${nodeIncludePosix}"
    - "-DNAPI_DISABLE_CPP_EXCEPTIONS"
`;

fs.writeFileSync(clangdPath, content, "utf8");
